/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_craftinginterpreters_lox_Lox */

#ifndef _Included_com_craftinginterpreters_lox_Lox
#define _Included_com_craftinginterpreters_lox_Lox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_craftinginterpreters_lox_Lox
 * Method:    compileJit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_craftinginterpreters_lox_Lox_compileJit
  (JNIEnv *, jclass);

/*
 * Class:     com_craftinginterpreters_lox_Lox
 * Method:    runJit
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_craftinginterpreters_lox_Lox_runJit
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
